=== chabeka/test5/sae/sae-webservices/src/main/resources/META-INF/SaeService.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sae="http://www.cirtil.fr/saeService" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.cirtil.fr/saeService">
    <xsd:element name="PingRequest">
        <xsd:annotation>
            <xsd:documentation>Requête de Ping (compatibilité ascendante)</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="PingResponse">
        <xsd:annotation>
            <xsd:documentation>Réponse de Ping : chaîne de caractères (compatibilité ascendante)</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="pingString" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="PingSecureRequest">
        <xsd:annotation>
            <xsd:documentation>Requête de PingSecure (compatibilité ascendante)</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="PingSecureResponse">
        <xsd:annotation>
            <xsd:documentation>Réponse de PingSecure : chaîne de caractères (compatibilité ascendante)</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="pingString" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:simpleType name="uuidType">
        <xsd:annotation>
            <xsd:documentation>UUID (Unique Universal Identifier) encodé sous forme hexadécimale, par exemple f81d4fae-7dec-11d0-a765-00a0c91e6bf6</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="ecdeUrlType">
        <xsd:annotation>
            <xsd:documentation>Une URL pointant sur l'ECDE, de la forme ecde://ecdeX/numeroCS/dateTraitement/documents/nom_du_fichier</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:anyURI">
            <xsd:pattern value="ecde://.*/.*/(19|20)[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])/[^/|\\]*/documents/.+"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="ecdeUrlSommaireType">
        <xsd:annotation>
            <xsd:documentation>Une URL pointant sur le fichier sommaire.xml d'un traitement de masse, de la forme ecde://ecdeX/numeroCS/dateTraitement/sommaire.xml</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:anyURI">
            <xsd:pattern value="ecde://.*/.*/(19|20)[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])/[^/|\\]*/sommaire.xml"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="objetNumeriqueType">
        <xsd:annotation>
            <xsd:documentation>Un objet numérique peut être représenté soit par son URL ECDE, soit par un flux binaire encodé en base64</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:choice>
                <xsd:element name="url" type="sae:ecdeUrlType"/>
                <xsd:element name="contenu" type="xsd:base64Binary"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="metadonneeCodeType">
        <xsd:annotation>
            <xsd:documentation>Code d'une métadonnée (identifiant unique) sous la forme d'une chaîne de caractères non vide.</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="metadonneeValeurType">
        <xsd:annotation>
            <xsd:documentation>Valeur d'une métadonnée sous la forme d'une chaîne de caractères qui peut être vide</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
    <xsd:complexType name="metadonneeType">
        <xsd:annotation>
            <xsd:documentation>Une métadonnée définie par un code et une valeur</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="code" type="sae:metadonneeCodeType">
                <xsd:annotation>
                    <xsd:documentation>Le code de la métadonnée (identifiant unique)</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="valeur" type="sae:metadonneeValeurType">
                <xsd:annotation>
                    <xsd:documentation>La valeur de la métadonnée (la valeur peut être vide)</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="listeMetadonneeType">
        <xsd:annotation>
            <xsd:documentation>Une liste de métadonnées</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="metadonnee" type="sae:metadonneeType">
                <xsd:annotation>
                    <xsd:documentation>Les métadonnées</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="listeMetadonneeCodeType">
        <xsd:annotation>
            <xsd:documentation>Une liste de codes de métadonnées</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="metadonneeCode" type="sae:metadonneeCodeType">
                <xsd:annotation>
                    <xsd:documentation>Les codes des métadonnées</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="requeteRechercheType">
        <xsd:annotation>
            <xsd:documentation>Une requête de recherche (chaîne non vide)</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="resultatRechercheType">
        <xsd:annotation>
            <xsd:documentation>Un résultat de la recherche de documents</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="idArchive" type="sae:uuidType">
                <xsd:annotation>
                    <xsd:documentation>L'identifiant unique d'archivage</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="metadonnees" type="sae:listeMetadonneeType">
                <xsd:annotation>
                    <xsd:documentation>La liste des métadonnées associées</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="listeResultatRechercheType">
        <xsd:annotation>
            <xsd:documentation>Liste de résultat d'une recherche de documents</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="resultat" type="sae:resultatRechercheType">
                <xsd:annotation>
                    <xsd:documentation>Les résultats de la recherche</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="archivageUnitaireRequestType">
        <xsd:annotation>
            <xsd:documentation>Paramètre d'entrée de l'opération 'archivage unitaire'</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="ecdeUrl" type="sae:ecdeUrlType">
                <xsd:annotation>
                    <xsd:documentation>L'objet numérique à archiver sous la forme d'une URL pointant vers un fichier de l'ECDE.</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="metadonnees" type="sae:listeMetadonneeType">
                <xsd:annotation>
                    <xsd:documentation>Les métadonnées. La liste peut être vide.</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="archivageUnitaireResponseType">
        <xsd:annotation>
            <xsd:documentation>Valeur de retour de l'opération 'archivage unitaire'</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="idArchive" type="sae:uuidType">
                <xsd:annotation>
                    <xsd:documentation>L'identifiant unique d'archivage</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="archivageMasseRequestType">
        <xsd:annotation>
            <xsd:documentation>Paramètre d'entrée de l'opération 'archivageMasse'</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="urlSommaire" type="sae:ecdeUrlSommaireType">
                <xsd:annotation>
                    <xsd:documentation>L'URL ECDE du fichier sommaire.xml décrivant le traitement de masse</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="archivageMasseResponseType">
        <xsd:annotation>
            <xsd:documentation>Valeur de retour de l'opération 'archivageMasse'. Le type est vide, il sert simplement à respecter la convention Document/Literal Wrapped pour le service web dans lequel il sera utilisé</xsd:documentation>
        </xsd:annotation>
    </xsd:complexType>
    <xsd:complexType name="rechercheRequestType">
        <xsd:sequence>
            <xsd:element name="requete" type="sae:requeteRechercheType">
                <xsd:annotation>
                    <xsd:documentation>La requête de recherche</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="metadonnees" type="sae:listeMetadonneeCodeType">
                <xsd:annotation>
                    <xsd:documentation>La liste des codes des métadonnées voulues</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="rechercheResponseType">
        <xsd:sequence>
            <xsd:element name="resultats" type="sae:listeResultatRechercheType">
                <xsd:annotation>
                    <xsd:documentation>Les résultats de la recherche. La liste peut être vide si aucun document n'a été retrouvé</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="resultatTronque" type="xsd:boolean">
                <xsd:annotation>
                    <xsd:documentation>Flag indiquant si la liste de résultats a été automatiquement tronquée car trop volumineuse</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="consultationRequestType">
        <xsd:sequence>
            <xsd:element name="idArchive" type="sae:uuidType">
                <xsd:annotation>
                    <xsd:documentation>L'identifiant unique d'archivage de l'archive à consulter</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="consultationResponseType">
        <xsd:sequence>
            <xsd:element name="objetNumerique" type="sae:objetNumeriqueConsultationType">
                <xsd:annotation>
                    <xsd:documentation>L'objet numérique,  soit directement sous forme d'un flux binaire en base 64, soit sous forme d'une URL de consultation directe. </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="metadonnees" type="sae:listeMetadonneeType">
                <xsd:annotation>
                    <xsd:documentation>Les métadonnées associées à l'archive, sous forme d'une liste de paire clé/valeur</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="urlConsultationDirecteType">
        <xsd:annotation>
            <xsd:documentation>Une URL de consultation directe</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:anyURI"/>
    </xsd:simpleType>
    <xsd:complexType name="objetNumeriqueConsultationType">
        <xsd:annotation>
            <xsd:documentation>Un objet numérique représenté soit un flux binaire encodé en base 64, soit par une URL de consultation directe</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:choice>
                <xsd:element name="url" type="sae:urlConsultationDirecteType"/>
                <xsd:element name="contenu" type="xsd:base64Binary"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="archivageUnitaire" type="sae:archivageUnitaireRequestType"/>
    <xsd:element name="archivageUnitaireResponse" type="sae:archivageUnitaireResponseType"/>
    <xsd:element name="archivageMasse" type="sae:archivageMasseRequestType"/>
    <xsd:element name="archivageMasseResponse" type="sae:archivageMasseResponseType"/>
    <xsd:element name="recherche" type="sae:rechercheRequestType"/>
    <xsd:element name="rechercheResponse" type="sae:rechercheResponseType"/>
    <xsd:element name="consultation" type="sae:consultationRequestType"/>
    <xsd:element name="consultationResponse" type="sae:consultationResponseType"/>
</xsd:schema>

=== chabeka/test5/sae/sae-webservices/src/test/resources/tests_xsd/cas016.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Une valeur de trop dans les métadonnées -->
<sae:archivageUnitaire xmlns:sae="http://www.cirtil.fr/saeService" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cirtil.fr/saeService ..\SaeService.xsd">
	<sae:ecdeUrl>ecde://ecde.cer69.recouvt/contrat_service/20110524/numTraitement/documents/monFichier.txt</sae:ecdeUrl>
	<sae:metadonnees>
		<sae:metadonnee>
			<sae:code>mon_code</sae:code>
			<sae:valeur>ma_valeur</sae:valeur>
		</sae:metadonnee>
		<sae:metadonnee>
			<sae:code>mon_code2</sae:code>
			<sae:valeur>ma_valeur2</sae:valeur>
		</sae:metadonnee>
		<sae:metadonnee>
			<sae:code>mon_code3</sae:code>
			<sae:valeur>ma_valeur3</sae:valeur>
			<sae:valeur>ma_valeur3</sae:valeur>
		</sae:metadonnee>
	</sae:metadonnees>
</sae:archivageUnitaire>
